### ISSUE TITLE
db hint

### ISSUE THREAD

**Issue by vitaly-t** [dmdb/gisie#1]
по поводу такого кода:
```js
var sql = {
    rubric_all: fs.readFileSync('./sql/rubric_all.sql').toString(),
    rubric_by_rid: fs.readFileSync('./sql/rubric_by_rid.sql').toString(),
    org_by_oids: fs.readFileSync('./sql/org_by_oids.sql').toString(),
    oids_by_rid: fs.readFileSync('./sql/oids_by_rid.sql').toString(),
    oids_by_lids: fs.readFileSync('./sql/oids_by_lids.sql').toString(),
    contact_by_oid: fs.readFileSync('./sql/contact_by_oid.sql').toString(),
    rubric_by_oid: fs.readFileSync('./sql/rubric_by_oid.sql').toString(),
    oids_by_title: fs.readFileSync('./sql/oids_by_title.sql').toString(),
    location_all: fs.readFileSync('./sql/location_all.sql').toString()
};
```
Тип [QueryFile](http://vitaly-t.github.io/pg-promise/QueryFile.html) встроенный в pg-promise это делает намного лучше.

Он может автоматически минимизировать скрипты при загрузке, и все методы запросов поддерживают его автоматически, но самое интересное - в режиме `debug` он автоматически подкачивает скрипты, т.е. не нужно прилад перезапускать после изменения внешних SQL файлов.

**Comment by dmdb** [comment]
спасибо!

**Comment by vitaly-t** [comment]
@dmdb пожалуйста!

И еще - использование промисов без `.catch` приведет к ненадежному коду ;)
